---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.apps.v1
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.autoscaling.v2beta1
  resources:
  - hpa
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.core.v1
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubeoperator.local
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubeoperator.local
  resources:
  - apps/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kubeoperator.local
  resources:
  - apps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io.kubeoperator.local
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io.kubeoperator.local
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io.kubeoperator.local
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
